[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_staking2022 = "4joSmR2pA9AevRzbjArQpiju5R8YXT5KYXLpsBKFBZRm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/zule/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
