[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_lottery = "Fk8Ht5g2mWbSBbbxU7kn6Ss7LisBnQPDZK6k5Mzn9Cre"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/zule/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
